// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSdsXaj4aTCsSSljd_b3-GvIV7veppg0',
    appId: '1:741203686068:web:137d2d8be5e40c40d39de1',
    messagingSenderId: '741203686068',
    projectId: 'sybeautyspa-e6cc5',
    authDomain: 'sybeautyspa-e6cc5.firebaseapp.com',
    storageBucket: 'sybeautyspa-e6cc5.appspot.com',
    measurementId: 'G-J1WH1P2J3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRMrhexaZ4GajGx22Z9Qwbrldwx6hqqk',
    appId: '1:741203686068:android:9d607d5bb7e89e87d39de1',
    messagingSenderId: '741203686068',
    projectId: 'sybeautyspa-e6cc5',
    storageBucket: 'sybeautyspa-e6cc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFlo-9fYm-SpEPeCrxzAhxXWQloofO2tQ',
    appId: '1:741203686068:ios:5f5feff019ec9a69d39de1',
    messagingSenderId: '741203686068',
    projectId: 'sybeautyspa-e6cc5',
    storageBucket: 'sybeautyspa-e6cc5.appspot.com',
    iosBundleId: 'com.example.beautySpa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFlo-9fYm-SpEPeCrxzAhxXWQloofO2tQ',
    appId: '1:741203686068:ios:42ceac02c5259f85d39de1',
    messagingSenderId: '741203686068',
    projectId: 'sybeautyspa-e6cc5',
    storageBucket: 'sybeautyspa-e6cc5.appspot.com',
    iosBundleId: 'com.example.beautySpa.RunnerTests',
  );
}
